Address
Anuradha-yadav169/demo pull request #3
Opened 2022-06-21 10:04 UTC by Anuradha-yadav169

2022-06-27 09:07 UTC, Nimish20 requested changes
@Anuradha-yadav169, please look at the below comments and address the issues that need to be addressed.

2022-06-27 09:07 UTC, Nimish20 commented on app/views/layouts/application.html.erb
> +    <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
@Anuradha-yadav169, please use single quotes for a simple string.

2022-06-27 09:07 UTC, Nimish20 commented on app/views/layouts/application.html.erb
> +    <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
@Anuradha-yadav169, please use the correct indentation.

2022-06-27 09:07 UTC, Nimish20 commented on app/views/addresses/show.html.erb
>              <div>
Please use the correct indentation.

2022-06-27 09:07 UTC, Nimish20 commented on app/controllers/application_controller.rb
> +  def update_allowed_parameters
@Anuradha-yadav169, what is the purpose of this filter?

2022-06-27 09:07 UTC, Nimish20 commented on app/controllers/addresses_controller.rb
> +      #@addresses = current_user.addresses.find(params[:id])
Please remove unnecessary comments.

2022-06-27 10:08 UTC, Anuradha-yadav169 commented on app/controllers/application_controller.rb
> +  def update_allowed_parameters
The name and surname fields on the user record were not saved. This is because we need to explicitly tell rails to accept these two fields in the form.

2022-06-29 04:49 UTC, Nimish20 requested changes
@Anuradha-yadav169, please fix the indentation on the view files.

2022-06-29 06:44 UTC, Nimish20 approved these changes

2022-06-29 06:44 UTC, merged